### ISSUE TITLE
Sample projects are using an outdated auth0-spring-mvc dependency and lock version. OIDC option is missing.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-spring-mvc-sample#11]
Latest version is auth0-spring-mvc-1.2.0
Projects:
01-login file pom.xml auth0-spring-mvc version 1.1.2 line: 66
09-mfa file pom.xml auth0-spring-mvc version 1.1.2 line 66

Lock version:
Project 01-login is using the version 10.11
![image](https://cloud.githubusercontent.com/assets/26749061/26138317/58b795e6-3a96-11e7-8e15-14a1c92e92ca.png)

Project 09-mfa is using the version 10.0
![image](https://cloud.githubusercontent.com/assets/26749061/26138448/46ff4a00-3a97-11e7-9fb7-be1687970187.png)

OIDC option is missing in the Lock's options.
![image](https://cloud.githubusercontent.com/assets/26749061/26138635/a6939574-3a98-11e7-9663-c36c68572b00.png)

**Comment by jimmyjames** [comment]
Hi @HeikerAraujo, as this sample and its supporting SDKs have changed since reporting, I'm going to close this issue. If you continue to have difficulties, don't hesitate to reopen this issue or create a new one (just be sure to include updated debugging information). Thanks!
