### ISSUE TITLE
could you please add example code to persist login data

### ISSUE THREAD

**Issue by DachengChen** [auth0-samples/auth0-spring-mvc-sample#34]
I have already add following setting in session
server.session.persistent=true

but it looks like after restart the application, the login data can not remember

thanks :D

**Comment by jimmyjames** [comment]
Hi @DachengChen, 

We want to keep the sample code fairly simple and focused on the key elements of adding Authentication to an app using Auth0, so I don't think we're going to add sticky sessions to the sample app. Persisting session data could be accomplished in a variety of ways depending on your application's requirements.

FWIW, for this sample that uses Tomcat, I think the property you want to set is `server.servlet.session.persistent=true`. 👍
